# Generated by Django 3.1.7 on 2021-04-17 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.PositiveIntegerField(null=True)),
                ('id_medico', models.PositiveIntegerField(null=True)),
                ('nome_paciente', models.CharField(max_length=40, null=True)),
                ('nome_medico', models.CharField(max_length=40, null=True)),
                ('data', models.DateTimeField(null=True)),
                ('descricao', models.TextField(max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, null=True)),
                ('endereco', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('fone', models.CharField(max_length=20, null=True)),
                ('sintomas', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=15, null=True)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('fone', models.CharField(max_length=20, null=True)),
                ('especialidade', models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Clínico Geral', 'Clínico Geral'), ('Dermatologista', 'Dermatologista'), ('Ortopedista', 'Ortopedista')], max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
