# Generated by Django 3.1.7 on 2021-04-10 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210404_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nome',
        ),
        migrations.AddField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_medico',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_paciente',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_paciente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Dermatologista', 'Dermatologista'), ('Clínico Geral', 'Clínico Geral'), ('Ortopedista', 'Ortopedista')], max_length=50, null=True),
        ),
    ]
