# Generated by Django 3.1.7 on 2021-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210410_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='nome_medico',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='assignedDoctorId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nome_paciente',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Clínico Geral', 'Clínico Geral'), ('Dermatologista', 'Dermatologista'), ('Ortopedista', 'Ortopedista')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
