# Generated by Django 3.1.7 on 2021-04-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210411_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
